# Using the data to create a composite index
## Creating a ratio to find relative difference between men and women
### PLFS data
Since the data has all india and Jammu and kashmir which is an UT and is missing from plfs data we should remove it to keep the normalisation accurate

In [2]:
import pandas as pd
workforce_df = pd.read_csv("cleaned_data/workforce_difference_women_and_men.csv")
workforce_df["state_name"] = workforce_df["state_name"].replace({"Himachal Pradesh":"Himachal"})
workforce_df["state_name"] = workforce_df["state_name"].replace({"Maharastra":"Maharashtra"})
workforce_df = workforce_df.drop(index=[0,9])
workforce_df = workforce_df.reset_index(drop=True)
workforce_df

        state_name  female_points  male_points
0   Andhra Pradesh           20.3         54.0
1            Assam           13.4         52.3
2            Bihar            3.2         45.2
3     Chhattisgarh           18.3         59.1
4            Delhi           16.0         55.0
5          Gujarat           17.6         66.7
6          Haryana           14.1         59.2
7         Himachal           18.4         56.5
8        Jharkhand            6.9         55.6
9        Karnataka           16.8         67.5
10          Kerala           27.0         53.0
11  Madhya Pradesh            9.1         53.1
12     Maharashtra           19.5         58.5
13          Odisha           20.9         59.3
14          Punjab           19.2         67.4
15       Rajasthan           12.2         57.2
16      Tamil Nadu           21.4         57.9
17       Telangana           20.6         58.7
18     Uttarakhand           14.7         56.8
19   Uttar Pradesh            7.7         56.4
20     West Bengal           21.4         63.1

To find how much more women work compared to men we shall find a ratio by women/men and then normalise the data to a scale of 0 to 1 to facilitate comparison under non apples to apples comparison
since we are finding the highest to lowest inequal states, states with high ratio near 1 have are more equal thus the normalisation index should represent them as 0 meaning least inequal state.

In [3]:
workforce_df["ratio"] = workforce_df["female_points"] / workforce_df["male_points"]
workforce_df["normal"] =1 -( (workforce_df["ratio"] - workforce_df["ratio"].min()) / (workforce_df["ratio"].max() - workforce_df["ratio"].min()))
workforce_df

        state_name  female_points  male_points     ratio    normal
0   Andhra Pradesh           20.3         54.0  0.375926  0.304370
1            Assam           13.4         52.3  0.256214  0.577287
2            Bihar            3.2         45.2  0.070796  1.000000
3     Chhattisgarh           18.3         59.1  0.309645  0.455477
4            Delhi           16.0         55.0  0.290909  0.498190
5          Gujarat           17.6         66.7  0.263868  0.559838
6          Haryana           14.1         59.2  0.238176  0.618411
7         Himachal           18.4         56.5  0.325664  0.418957
8        Jharkhand            6.9         55.6  0.124101  0.878478
9        Karnataka           16.8         67.5  0.248889  0.593987
10          Kerala           27.0         53.0  0.509434  0.000000
11  Madhya Pradesh            9.1         53.1  0.171375  0.770703
12     Maharashtra           19.5         58.5  0.333333  0.401472
13          Odisha           20.9         59.3  0.352445  0.357901
14          Punjab           19.2         67.4  0.284866  0.511966
15       Rajasthan           12.2         57.2  0.213287  0.675153
16      Tamil Nadu           21.4         57.9  0.369603  0.318785
17       Telangana           20.6         58.7  0.350937  0.361339
18     Uttarakhand           14.7         56.8  0.258803  0.571386
19   Uttar Pradesh            7.7         56.4  0.136525  0.850153
20     West Bengal           21.4         63.1  0.339144  0.388224

In [4]:
workforce_df= workforce_df.rename(columns={"normal":"workforce_inequality"})
workforce_df.head()

       state_name  female_points  male_points     ratio  workforce_inequality
0  Andhra Pradesh           20.3         54.0  0.375926              0.304370
1           Assam           13.4         52.3  0.256214              0.577287
2           Bihar            3.2         45.2  0.070796              1.000000
3    Chhattisgarh           18.3         59.1  0.309645              0.455477
4           Delhi           16.0         55.0  0.290909              0.498190

### TUS data

In [5]:
tus_df = pd.read_csv("cleaned_data/TUS_domestic_service.csv")
tus_df = tus_df.drop(index=[1,6,15,16,17,18,22,25])
tus_df["state_name"] = tus_df["state_name"].replace({"Madya Pradesh":"Madhya Pradesh"})
tus_df["state_name"] = tus_df["state_name"].replace({"Maharastra":"Maharashtra"})
tus_df["state_name"] = tus_df["state_name"].replace({"Gujrat":"Gujarat"})
tus_df = tus_df.reset_index(drop=True)
tus_df

        state_name  male  female
0   Andhra Pradesh    79     257
1            Assam    99     357
2            Bihar    89     386
3     Chhattisgarh    94     269
4            Delhi   113     343
5          Gujarat    99     310
6          Haryana    94     302
7         Himachal   118     268
8        Jharkhand    99     341
9        Karnataka    81     320
10          Kerala    86     296
11  Madhya Pradesh   116     310
12     Maharashtra    90     299
13          Odisha    91     332
14          Punjab    98     353
15       Rajasthan   104     297
16      Tamil Nadu    77     254
17       Telangana    77     235
18   Uttar Pradesh   105     326
19     Uttarakhand   101     315
20     West Bengal   100     353

Now we have to translate the diffrence by taking a ratio and normalising again

In [6]:
tus_df["ratio"] = tus_df["female"] / tus_df["male"]
tus_df.head()

       state_name  male  female     ratio
0  Andhra Pradesh    79     257  3.253165
1           Assam    99     357  3.606061
2           Bihar    89     386  4.337079
3    Chhattisgarh    94     269  2.861702
4           Delhi   113     343  3.035398

the number closer to 1 is the state with most equality this we must assign 1 to least inequal state or the states with the higest ratio number must be 1

In [7]:
tus_df["normal"] =(tus_df["ratio"] - tus_df["ratio"].min()) / (tus_df["ratio"].max() - tus_df["ratio"].min())
tus_df

        state_name  male  female     ratio    normal
0   Andhra Pradesh    79     257  3.253165  0.475329
1            Assam    99     357  3.606061  0.646149
2            Bihar    89     386  4.337079  1.000000
3     Chhattisgarh    94     269  2.861702  0.285841
4            Delhi   113     343  3.035398  0.369919
5          Gujarat    99     310  3.131313  0.416346
6          Haryana    94     302  3.212766  0.455774
7         Himachal   118     268  2.271186  0.000000
8        Jharkhand    99     341  3.444444  0.567918
9        Karnataka    81     320  3.950617  0.812932
10          Kerala    86     296  3.441860  0.566668
11  Madhya Pradesh   116     310  2.672414  0.194215
12     Maharashtra    90     299  3.322222  0.508756
13          Odisha    91     332  3.648352  0.666620
14          Punjab    98     353  3.602041  0.644203
15       Rajasthan   104     297  2.855769  0.282969
16      Tamil Nadu    77     254  3.298701  0.497371
17       Telangana    77     235  3.051948  0.377930
18   Uttar Pradesh   105     326  3.104762  0.403494
19     Uttarakhand   101     315  3.118812  0.410295
20     West Bengal   100     353  3.530000  0.609332

In [8]:
tus_df= tus_df.rename(columns={"normal":"unpaid_labour"})
tus_df.head()

       state_name  male  female     ratio  unpaid_labour
0  Andhra Pradesh    79     257  3.253165       0.475329
1           Assam    99     357  3.606061       0.646149
2           Bihar    89     386  4.337079       1.000000
3    Chhattisgarh    94     269  2.861702       0.285841
4           Delhi   113     343  3.035398       0.369919

### political represnetation of women in states

In [9]:
pol_df = pd.read_csv("cleaned_data/prs_political_participation.csv")
pol_df = pol_df.rename(columns={'States':'state_name'})
pol_df["state_name"] = pol_df["state_name"].replace({"Madya Pradesh":"Madhya Pradesh"})
pol_df["state_name"] = pol_df["state_name"].replace({"Maharastra":"Maharashtra"})
pol_df["state_name"] = pol_df["state_name"].replace({"Gujrat":"Gujarat"})
pol_df = pol_df.drop(index=[1,6,15,16,17,18,22,25])
pol_df = pol_df.reset_index(drop=True)
pol_df

        state_name  Women_pct
0   Andhra Pradesh          9
1            Assam          5
2            Bihar         12
3     Chhattisgarh         18
4            Delhi         10
5          Gujarat          8
6          Haryana         10
7         Himachal          1
8        Jharkhand         12
9        Karnataka          4
10          Kerala          9
11  Madhya Pradesh          9
12     Maharashtra          8
13          Odisha         12
14          Punjab         11
15       Rajasthan         14
16      Tamil Nadu          5
17       Telangana          5
18   Uttar Pradesh         12
19     Uttarakhand         13
20     West Bengal         14

Now to be consistant we need to use ratio of women%/men% but since there is no men% data we ought to subtract 1- women % to get the required value

In [10]:
pol_df["Men_pct"] = 100 - pol_df["Women_pct"]
pol_df.head()

       state_name  Women_pct  Men_pct
0  Andhra Pradesh          9       91
1           Assam          5       95
2           Bihar         12       88
3    Chhattisgarh         18       82
4           Delhi         10       90

In [11]:
pol_df["ratio"] = pol_df["Women_pct"] / pol_df["Men_pct"]
pol_df.head()

       state_name  Women_pct  Men_pct     ratio
0  Andhra Pradesh          9       91  0.098901
1           Assam          5       95  0.052632
2           Bihar         12       88  0.136364
3    Chhattisgarh         18       82  0.219512
4           Delhi         10       90  0.111111

states with equal represtation must have 50-50 share of power and thus equal states should have ratio of 1 and unequal states have 0. Any states with ratio more than 1 mean that state has more women participation but this cannot be seen in this data

In [12]:
pol_df["normal"] = (1- (pol_df["ratio"] - pol_df["ratio"].min()) / (pol_df["ratio"].max() - pol_df["ratio"].min()))
pol_df

        state_name  Women_pct  Men_pct     ratio    normal
0   Andhra Pradesh          9       91  0.098901  0.575953
1            Assam          5       95  0.052632  0.796904
2            Bihar         12       88  0.136364  0.397059
3     Chhattisgarh         18       82  0.219512  0.000000
4            Delhi         10       90  0.111111  0.517647
5          Gujarat          8       92  0.086957  0.632992
6          Haryana         10       90  0.111111  0.517647
7         Himachal          1       99  0.010101  1.000000
8        Jharkhand         12       88  0.136364  0.397059
9        Karnataka          4       96  0.041667  0.849265
10          Kerala          9       91  0.098901  0.575953
11  Madhya Pradesh          9       91  0.098901  0.575953
12     Maharashtra          8       92  0.086957  0.632992
13          Odisha         12       88  0.136364  0.397059
14          Punjab         11       89  0.123596  0.458030
15       Rajasthan         14       86  0.162791  0.270862
16      Tamil Nadu          5       95  0.052632  0.796904
17       Telangana          5       95  0.052632  0.796904
18   Uttar Pradesh         12       88  0.136364  0.397059
19     Uttarakhand         13       87  0.149425  0.334686
20     West Bengal         14       86  0.162791  0.270862

In [13]:
pol_df= pol_df.rename(columns={"normal":"political_inequality"})
pol_df.head()

       state_name  Women_pct  Men_pct     ratio  political_inequality
0  Andhra Pradesh          9       91  0.098901              0.575953
1           Assam          5       95  0.052632              0.796904
2           Bihar         12       88  0.136364              0.397059
3    Chhattisgarh         18       82  0.219512              0.000000
4           Delhi         10       90  0.111111              0.517647

In [14]:
index_df = pd.merge(pol_df, tus_df, on='state_name', how='inner')
print(index_df.shape)
index_df = pd.merge(index_df, workforce_df, on='state_name', how='inner')
print(index_df.shape)
index_df.head()

(21, 9)
(21, 13)

,state_name,Women_pct,Men_pct,ratio_x,political_inequality,male,female,ratio_y,unpaid_labour,female_points,male_points,ratio,workforce_inequality
0,Andhra Pradesh,9,91,0.098901,0.575953,79,257,3.253165,0.475329,20.3,54.0,0.375926,0.304370
1,Assam,5,95,0.052632,0.796904,99,357,3.606061,0.646149,13.4,52.3,0.256214,0.577287
2,Bihar,12,88,0.136364,0.397059,89,386,4.337079,1.000000,3.2,45.2,0.070796,1.000000
3,Chhattisgarh,18,82,0.219512,0.000000,94,269,2.861702,0.285841,18.3,59.1,0.309645,0.455477
4,Delhi,10,90,0.111111,0.517647,113,343,3.035398,0.369919,16.0,55.0,0.290909,0.498190

In [15]:
index_df= index_df.loc[:,['state_name','political_inequality','unpaid_labour','workforce_inequality']]
index_df.head()

       state_name  political_inequality  unpaid_labour  workforce_inequality
0  Andhra Pradesh              0.575953       0.475329              0.304370
1           Assam              0.796904       0.646149              0.577287
2           Bihar              0.397059       1.000000              1.000000
3    Chhattisgarh              0.000000       0.285841              0.455477
4           Delhi              0.517647       0.369919              0.498190

In [16]:
index_df["oddhouse_index"] = (index_df["political_inequality"]
                            + index_df["unpaid_labour"]
                            +index_df["workforce_inequality"])/3
oddhouse_index = index_df
oddhouse_index.to_csv("oddhouse_index.csv", index = False)
oddhouse_index = oddhouse_index.sort_values(by='oddhouse_index', ascending=False)
oddhouse_index.to_csv("oddhouse_index_ordered.csv", index = False)
oddhouse_index.head(10)

,state_name,political_inequality,unpaid_labour,workforce_inequality,oddhouse_index
2,Bihar,0.397059,1.000000,1.000000,0.799020
9,Karnataka,0.849265,0.812932,0.593987,0.752061
1,Assam,0.796904,0.646149,0.577287,0.673447
8,Jharkhand,0.397059,0.567918,0.878478,0.614485
18,Uttar Pradesh,0.397059,0.403494,0.850153,0.550235
14,Punjab,0.458030,0.644203,0.511966,0.538067
16,Tamil Nadu,0.796904,0.497371,0.318785,0.537687
5,Gujarat,0.632992,0.416346,0.559838,0.536392
6,Haryana,0.517647,0.455774,0.618411,0.530611
12,Maharashtra,0.632992,0.508756,0.401472,0.514407